{
  "openapi": "3.0.1",
  "info": {
    "title": "API V1",
    "version": "v1"
  },
  "security": [
    {
      "api_key": [

      ]
    }
  ],
  "paths": {
    "/developers": {
      "get": {
        "summary": "list of developers",
        "tags": [
          "developers"
        ],
        "security": [
          {
            "api_key": [

            ]
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "count": {
                      "type": "integer"
                    },
                    "records": {
                      "type": "array"
                    }
                  },
                  "required": [
                    "count",
                    "records"
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    },
    "/developers/{id}": {
      "get": {
        "summary": "get a developer",
        "tags": [
          "developers"
        ],
        "security": [
          {
            "api_key": [

            ]
          }
        ],
        "parameters": [
          {
            "name": "id",
            "in": "path",
            "required": true,
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "OK",
            "content": {
              "application/json": {
                "schema": {
                  "type": "object",
                  "properties": {
                    "id": {
                      "type": "integer"
                    },
                    "name": {
                      "type": "string"
                    },
                    "age": {
                      "type": "integer"
                    },
                    "created_at": {
                      "type": "string"
                    },
                    "updated_at": {
                      "type": "string"
                    }
                  },
                  "required": [
                    "id",
                    "name",
                    "age",
                    "created_at",
                    "updated_at"
                  ]
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized"
          }
        }
      }
    }
  },
  "servers": [
    {
      "url": "{connectionType}//{defaultHost}",
      "variables": {
        "defaultHost": {
          "default": "www.example.com"
        },
        "connectionType": {
          "default": "http:",
          "enum": [
            "http:",
            "https:"
          ]
        }
      }
    }
  ],
  "components": {
    "securitySchemes": {
      "api_key": {
        "type": "apiKey",
        "name": "Authorization",
        "in": "header"
      }
    }
  }
}